### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by skiesx** [MrS0m30n3/google-translate#3]
I run this command:
`pip3 install doodle-translate`
after. i have this error:
```
Collecting doodle-translate
  Using cached doodle-translate-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dqcfzf_p/doodle-translate/setup.py", line 8, in <module>
        from google_translate import (
      File "/tmp/pip-build-dqcfzf_p/doodle-translate/google_translate/__init__.py", line 44, in <module>
        from .translator import GoogleTranslator
      File "/tmp/pip-build-dqcfzf_p/doodle-translate/google_translate/translator.py", line 31
        print error
                  ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dqcfzf_p/doodle-translate/

```
Help me, please)

**Comment by MrS0m30n3** [comment]
Read https://github.com/MrS0m30n3/google-translate/issues/1
